SELECT
	TEAM_ABBREVIATION
FROM
	(SELECT
		TEAM_ABBREVIATION,
		COUNT(PLAYER_NAME) as player_count,
		RANK() OVER(ORDER BY COUNT(PLAYER_NAME) DESC) as rankings
	FROM
		(SELECT
			PLAYER_NAME,
			TEAM_ABBREVIATION,
			SUM(PTS*GP) as player_points
		FROM
			dbo.nba_stats
		GROUP BY
			PLAYER_NAME,
			TEAM_ABBREVIATION
		HAVING
			SUM(PTS*GP) >= 750) temp
	GROUP BY
		TEAM_ABBREVIATION) temp2
WHERE
	rankings = 1